# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tapioca` gem.
# Please instead update this file by running `bin/tapioca gem tapioca`.

# source://tapioca-0.9.4/lib/tapioca/version.rb:5
Tapioca::VERSION = T.let(T.unsafe(nil), String)
